### ISSUE TITLE
How to make Token as per the paper

### ISSUE THREAD

**Issue by IkumaUchida** [zhengwang125/play2vec#3]
### Summary
Hello, I have a question again .

I am currently creating a corpus in building.py according to play2vec's readme.
I want to create tokens for the volumes listed in table 7 of the play2vec paper (num of raw data = 7500, cell size = 3m , #tokens = 50465)
![スクリーンショット 2022-06-23 21 44 55](https://user-images.githubusercontent.com/48281753/175301528-1f72e48b-d8e6-4930-a288-4eba50488f3a.png)

However, in the script, I implemented the cell size, Jaccard index threshold and short duration to match the paper, but the number of tokens is significantly different from the paper's number.
(num of raw data =7500, #tokens = 24155)

Please let me ask two questions to make the token quantity match.
1. play2vec's missing process (`corrupted_drop.py`) and noise process (`corrupted_noise.py`) were hard-coded as ratio=0.2. However, Table 7 in the paper shows that r_n=r_d=0.5.
Should this be adjusted to the paper's ratio?.

2. to create a corpus with #tokens = 50465, which preprocessing data (noise or drop) should I add as input data? It does not seem to have been mentioned in the paper which blend was used to obtain the results in Table 7.

Note that in the implementation, line 14 of `building.py` blends `ogm_train_data` (the index of the segment matrix of the raw data) and `cor_ogm_train_data `(the index of the segment matrix of the processed data).
https://github.com/zhengwang125/play2vec/blob/ca4af2e9e2701a748c2383fae4410601853eebbb/building.py#L14

Or should I add both of the processed data?
That is, should it be in the form `senbag = ogm_train_data + cor_ogm_train_data_noise + cor_ogm_train_data_drop`?

Also, if there is some other reason why the corpus is not being created properly, I would appreciate it if you could tell me as much as you can remember.

**Comment by zhengwang125** [comment]
Cannot remember very detailed codes. If the quantity is around 2 times, it may as your mentioned with a larger ratio and blend. Because some new tokens may occur in the corrupted version, and the corpus should include them to obtain embeddings.

**Comment by IkumaUchida** [comment]
Thank you very much.
I would like to try under different conditions and search for values close to the paper.
